[theme]
base="light"
primaryColor="#2769a7"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#ebf0f2"
textColor="#333333"
font="sans serif"

[header]
backgroundColor="#00A6D6"
textColor="#FFFFFF"

[sidebar]
backgroundColor="#FFFFFF"
textColor="#333333"
separatorColor="#DDDDDD"
